server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: client-service

  profiles:
    active: native

feign:
  circuitbreaker:
    enabled: true

Lospring:
  sleuth:
    sampler:
      probability: 2.0