server:
  port: 4444
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      #      routes:
      #        id: client
      #      uri: lb://client-service
      #      predicates:
      #        - Path=/api/client/**
      #      filters:
      #        - RewritePath=/api/client/(?.*), /$\{remains}
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
Lospring:
  sleuth:
    sampler:
      probability: 2.0